### ISSUE TITLE
MARKER fails some tests

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#84] opened 2018-06-24 01:23 UTC
... those where **HERE** should be the same value before and after a place was marked and then returned to. This must be a development in the last few days, as it worked originally.

**Comment by SamCoVT** [comment] 2018-06-30 00:53
Some initial findings:
Marker seems to work fine from a cold start, a cold start followed by an allot, a cold start followed by the MARKER followed by an allot that crosses a page.

When a variable is declared before marker, the restored HERE has an MSB that it one too low and an LSB that is one too high.  It doesn't matter if you assign to the variable or not.

Here's an example test.

Tali Forth 2 comes with absolutely NO WARRANTY
Type 'bye' to exit
  ok
`: check ." HERE: " here . ."   UNUSED: " unused . ;`  ok
`check` HERE: 6549   UNUSED: 25195  ok
`hex`  ok
`check` HERE: 1995   UNUSED: 626B  ok
`marker quarian`  ok
`: marker_test ." Bosh'tet!" ;`  ok
`check` HERE: 19D3   UNUSED: 622D  ok
`marker_test` Bosh'tet! ok
`quarian`  ok
`check` HERE: 1995   UNUSED: 626B  ok
`( Worked fine this time. )`  ok               
`check` HERE: 1995   UNUSED: 626B  ok
`variable marker_size`  ok
`check` HERE: 1AAD   UNUSED: 6153  ok
`unused marker_size !`  ok
`check` HERE: 1AAD   UNUSED: 6153  ok
`marker quarian`  ok
`check` HERE: 1AC1   UNUSED: 613F  ok
`: marker_test ." Bosh'tet!" ;`  ok
`check` HERE: 1AEB   UNUSED: 6115  ok
`marker_test` Bosh'tet! ok
`check` HERE: 1AEB   UNUSED: 6115  ok
`quarian`  ok
`check` HERE: 19AE   UNUSED: 6252  ok
`( MSB is always one too low while LSB is one too high )`  ok
`( This only happens if the variable is declared first )`  ok

**Comment by SamCoVT** [comment] 2018-06-30 02:39
There is something funny with VARIABLE.

Isn't a variable just supposed to be a jsr to dovar: followed by the value?  That should be only 5 bytes (plus the nt, of course).  SEE shows something reasonable, but HERE is reporting the cp is way further along in memory.

It looks to me like VARIABLE is incrementing the MSB of cp when it shouldn't.  See the SEEs below.  My variable a has xt starting at $199e with a size of 5, so it ends at $19a2.  The means CP should be at **19**a3, but you can see the next variable starts at **1a**a3 instead.

```
Type 'bye' to exit
: check ." HERE: " here . ."   UNUSED: " unused . ;      ok
hex check HERE: 1995   UNUSED: 626B  ok
check HERE: 1995   UNUSED: 626B  ok
variable a  ok
check HERE: 1AA3   UNUSED: 615D  ok
1aa3 1995 - . 10E  ok
variable b  ok
check HERE: 1BB1   UNUSED: 604F  ok
1bb1 1aa3 - . 10E  ok
variable w  ok
check HERE: 1CBF   UNUSED: 5F41  ok
1cbf 1bb1 - . 10E  ok

see a 
 nt: 1995  xt: 199E  NN 
 size (decimal): 5 
 
199E  20 16 B7 00 00 

199E  jsr B716
19A1  brk
19A2  brk
 ok
see b 
 nt: 1AA3  xt: 1AAC  NN 
 size (decimal): 5 
 
1AAC  20 16 B7 00 00 

1AAC  jsr B716
1AAF  brk
1AB0  brk
 ok
see w 
 nt: 1BB1  xt: 1BBA  NN 
 size (decimal): 5 
 
1BBA  20 16 B7 00 00 

1BBA  jsr B716
1BBD  brk
1BBE  brk
 ok
```

**Comment by SamCoVT** [comment] 2018-06-30 03:12
I think it's here.

```
xt_variable:    
                ; we let CREATE do the heavy lifting
                jsr xt_create

                ; there is no "STZ (CP)" so we have to do this the hard
                ; way
                lda #0
                sta (cp)
                inc cp
                bne +
                inc cp+1
*
                sta (cp)
                inc cp
                bne +
* ; <===== Did you want this * AFTER the inc cp+1?
                inc cp+1

                ; Now we need to adjust the length of the complete word by two
                jsr adjust_z
                
z_variable:     rts
```
I tried this fix, but it still fails the test, however it's only off by 1 now (LSB is still one to high).  I think the issue is that your code for  restoring cp in MARKER assumes that the address of z_word in the header is the address of an rts instruction, so it adds one to cp to make it point to just after the rts.  Variables don't have an RTS on the end, so z_word is actually just beyond the end of the data, and cp shouldn't be incremented.

There is a bigger issue here.  The current code assumes that if it can find the word just before the marker, then the z_word in that nt is where the dictionary should end.  What about code like:
```
variable a
100 allot
marker b
b
```
That will try to restore up until the "end" of a, which won't know about the extra space allotted in the dictionary.

Does it make sense to just store the actual values in dp and cp, and then restore them both when the marker word is invoked later?

That's all of the brain power I have tonight.  You should fix the * in xt_variable:, but I think there is still an issue here.

**Comment by scotws** [comment] 2018-06-30 06:30
Yeah, **VARIABLE** has an obvious typo there, thanks for that. Test after fix running as I type (and then I'm AFK for most of the rest of the day). 

In theory, **MARKER** is really simple - remember the CP, remember the DP, restore them; be able to handle multiple markers. I think you're right, whatever the fooling around with the adjustment is at the moment, we brute-force it and just store stuff. The good news is that we can have a run-time part of **MARKER** so the actual word will be smaller. I can do this (Sunday, I hope), or would you rather?

**Comment by SamCoVT** [comment] 2018-06-30 12:48
I'll let you fix that one up.

**Closed** 2018-07-01 06:33 UTC
Labels: bug
