### ISSUE TITLE
Allow S" to handle strings longer than 255 chars

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#20] opened 2018-05-03 21:36 UTC

**Comment by SamCoVT** [comment] 2018-06-09 16:12
Because ." just uses S" and then TYPE, they both should be able to be done by fixing S".  It looks like PARSE is used to find the end of the string (asking it to find the double quote char as a delimiter), but it looks like parse will end early if it finds the end of the input buffer first.  For truly long strings, S" is going to have to save them into the dictionary BEFORE it knows how long they are, and will have to deal with chewing through multiple input buffer refills while looking for the ending double-quote.  

Because S" will now need to do a lot of the work that PARSE was doing, does it make sense to also add code for S\\" as well?  It's a core-ext word (I'm not sure if you were planning on doing any of the core-ext words.)  They will have almost identical behavior except that S\\" will look for escaped (with a backslash) characters and replace them.  I could envision the same compile time code with a flag to toggle in/out the escaped character checks, and then identical runtime. I don't think any work on S" would preclude adding this later, so S\\" can certainly be added on later as a separate issue if you think you want it.

**Comment by scotws** [comment] 2018-06-10 03:47
I hadn't actually given `s\"` any thought so far -- I took one look at https://forth-standard.org/standard/core/Seq and decided to punt it, if I remember -- but if we get it that easy while rewriting `s"`, sure!

**Comment by SamCoVT** [comment] 2018-06-17 14:46
I'm gearing up to do this one next, but need some help working through a possible implementation to make sure I'm not going to break something I don't know about.

I think `S"` will now look a lot like `PARSE ( if passed the double-quote (") character )` with the following differences:

I think I'm planning on moving to a letter-by-letter copying of the input buffer as I can't use any of the 65c02's indexed modes and will need to use indirect mode instead.  The indexed modes are limited to offsets of 255 and I don't know the length of the string anyway.  

I'll also need to be able to refill the input buffer in case I reach the end before finding the double quote.  It looks like `REFILL` will update `ciblen` for me, so I just need to start at the beginning of `cib` (reset `toin` to 0) and then keep processing from there.  

The standard says that `REFILL` should reset `>IN` to zero, but Tali's doesn't - it looks like it's done in `ABORT`, which is the only place `REFILL` is currently called.  I'll add a separate issue for this, but I'll clean it up while working on this.

Once the string is on the stack, I need to be able to handle "literalizing" it with SLITERAL.  The issue is that it will already be in the dictionary BEFORE the name token.  Do you think it will be any problem to simply `cmpl_subroutine` the `sliteral_runtime` and then compiling in the address and the length right after (like sliteral_runtime expects)?  It would change the existing structure of a string literal in the dictionary from:
```
name token
jump over string
string data
call to sliteral
address
length
```
to
```
string data
name token
call to sliteral
address
length
```
I don't see where that would break anything.  I'm going to start heading down this path, so let me know if you see any stumbling blocks or extra things I should know about.

**Comment by SamCoVT** [comment] 2018-06-17 17:18
And, sure enough, that breaks things.  `S"` works fine in interpreted mode.  The issue is that, in compile mode, the name_token is already there in the dictionary (during the compiling of a word that has `S"` in it) before the data gets copied.
My super-sneaky thought is to always prefix constant strings stored in the dictionary with a jmp over them (similar to what you were doing before).

**Closed** 2018-06-19 12:51 UTC
Labels: todo
