### ISSUE TITLE
Possible spots to optimize for space

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#197] opened 2018-12-17 03:49 UTC
I believe the goal is to try to keep Tali under 24K.  With the recent addition of the assembler, we're kinda close to that now, so I figured I would open an issue to track spots that could be optimized at a later date.  This is intended as a kind of to-do list with an estimated number of bytes saved so that we can pick and choose at a later date, if we get to a point where we need to trim things down.  I don't expect all of them to be done.

SIZE | Optimization
--- | --- 
6 bytes | FORTH-WORDLIST could be linked to the runtime for xt_zero
6 bytes | EDITOR-WORDLIST could be linked to the runtime for xt_one
6 bytes | ASSEMBLER-WORDLIST could be linked to the runtime for xt_two
150ish | Make FIND-NAME call SEARCH-WORDLIST.  This is a bit tricky as SEARCH-WORDLIST has the silly return semantics of FIND, but it least it accepts the same modern type string as FIND-NAME.
70ish | Get rid of the ROOT-WORDLIST and go back to using FORTH-WORDLIST as the minimum search order wordlist.
??? | Double-check why SEARCH-WORDLIST is 50 bytes larger than FIND-NAME even though it only has to search one wordlist and FIND-NAME has to traverse the search order
1Kish? | Assemblerize more of the words (aka #14) in forth_words.fs as the current assemblerizing rate shrinks these to about 25-30% of their text size.  forth-words.asc is currently around 1.6K or so.

**Comment by SamCoVT** [comment] 2018-12-17 14:31
Size | Optimization
--- | ---
2 bytes | In asm_common in assembler.asm, you can change both CPY instructions checking the value of Y with a DEY instead.  This instruction sets the zero flag, so your BEQ will still work.  The cycle count is the same.
200+ bytes | Move underflow checking to a subroutine (#165)

**Comment by scotws** [comment] 2018-12-17 16:06
It's actually worse than it seems, because we need to leave some space for the `user_forth.fs` words (the Steckschwein people really liked that ability). We can probably assemblerize **see** from there as well for good savings.

I also think I have figured out a way to save a bunch of space through a rewite of **disasm**, I'll open a different issue for that later.

**Comment by SamCoVT** [comment] 2018-12-18 13:52
I've been rattling around in my head how to merge the assembler, disassembler, and dictionary, and this is what I've come up with.  It should save hundreds of bytes, at the expense of speed (of course).

Put the opcode as an extra byte after the name of the opcode in the dictionary.  `find-name` will still stop at the right place (because it honors the name length), but asm_common can be taught to look just after the name for the opcode.

You also need how long the instruction is, and there are conveniently two bytes left in the status field in the dictionary.  Use 00 for a regular word, 01 for a 1-byte assembly word, 10 for a two byte assembly word, and 11 for a three byte assembly word.  If you want to reserve those two bits, you could also use an extra byte right after the opcode.

The issue with the opcode in the dictionary (right after the name) is that asm_common will need access to the nt of the word currently being executed.  I thought of having the interpreter put it on the stack for words with status bits indicating they are assembly words, but this doesn't work if someone takes the the XT of an assembly word and tries to execute it.  

The only solution I can some up with for this is to have every word just contain `jsr asm_common`.  This allows jsr_common to pull the return address off the stack, do some math to turn it into the xt for the word, turn the xt into an nt (with int>name, which will be very slow), and then access the opcode and length hidden in the dictionary header.  With the assembly word's return address pulled of the stack, when asm_common returns it will return back to whoever called the asm word.

This adds 1 byte to the dictionary but removes 4 bytes from every assembler word.  The disassembler can crawl the ASSEMBLER-WORDLIST looking at the opcodes hidden after the name, and when it finds the right NT, it will have the name and the length right there.  It's waaaaaaaay slower than a lookup table, but requires no additional data, saving 512 bytes from the oc_index_table, and another few hundred bytes from the name and lengths in oc_table, which are now already duplicated in the dictionary.

These changes will seriously slow down the assembler and disassembler, but that may be a reasonable price to pay as the assembly created will be fast when run.  It might be worth testing a single word to see what the penalty of finding the NT this way is:  Running `' adc.# int>name` seems instantaneous in the simulator...  Let me cycle test it...
```
\ **************** SamCo Special Test  ok
assembler-wordlist >order  ok
' tya      ' int>name      cycle_test drop       CYCLES:  19753 ok
  ok
\ ***********************************  ok
\ **************** SamCo Special Test  ok
assembler-wordlist >order  ok
' adc.#      ' int>name      cycle_test drop       CYCLES:  31545 ok
  ok
\ ***********************************  ok
```
With a 4MHz clock, that's about 8ms for `adc.#`.  I chose `adc.#` because it is the last word in the assembler-wordlist.  int>name searches ALL of the wordlists and ignores the search order, so this actually looked through all of the forth-wordlist and editor-wordlist first.  I also ran `tya` above (it's the first assembler word in the assembler-wordlist) and got about 5ms (on a 4MHz clock).  I wouldn't try to compile Tali as these speeds, but it should be fine for developing new words.

**Comment by scotws** [comment] 2018-12-18 14:42
So we overlapped here, I just moved the assembler over to the opcode tables used in the disassembler. We went from 1.3 K for the assembler to about 950 bytes with that. 

The solution sounds very doable, and we should remember it if we get _really_ pressed for space because of the speed - I started out with a 1 MHz Übersquirrel on a breadboard, and if had been too slow, I probably would have wandered off and done something else :-).

Before we do that, we should probably work through your list above - **see** uses incredible 817 bytes, and **hexstore** 221, which just won't do. I'll take a look at **see** next.

What big parts do we still have? The block editor would seem to be the last big piece before Version 1.0, and after that we have the multitasking, which I have no feeling for how much space that will take.

**Comment by SamCoVT** [comment] 2018-12-18 15:02
Sorry for the long post (and for working on something you are working on), but it's been rattling around in my head (with nothing that actually works, for one reason or another, most of the time), so I wanted to document it when I finally thought of a possible solution.  You are welcome to disregard it, of course, but it does have some potential to save bytes if we need them, so I wrote it up.

That's a good savings on the assembler.

I'll start working on getting the block editor in assembly into the editor-wordlist so we can see where we are at.  Once I get that working, I can take another look at the words in forth_words.asc.  The sheer number of `POSTPONE` words scares me a bit as I'm not sure how that translates into assembly.

**Comment by scotws** [comment] 2018-12-18 17:56
Didn't we also want to initialize the system by copying stuff from ROM instead of our current LDA/STA method? Or is it still too early for that?

**Comment by SamCoVT** [comment] 2018-12-18 18:05
Now that I've shrunk the usage by the search order (by using byte variables where possible), it's probably a good time to look into that.  I'll add an issue for it and you can assign it to me.

**Comment by scotws** [comment] 2018-12-19 14:57
**Postpone** is a bad one to assemblerize, and I have been chickening out because of that. Some of the problem is described in the comment in `native-words.asm`. The short version is that we probably need to code an extra word from Gforth named **execute-parsing ( addr u xt -- )** (see https://www.complang.tuwien.ac.at/forth/gforth/Docs-html/The-Input-Stream.html). It's still going to be a pain.

I think it might be worth while after all to move the underflow check to a subroutine for a few hundred bytes, unless you're already on that I'll see about that next?

**Comment by SamCoVT** [comment] 2018-12-19 15:57
That sounds good.  I'm finishing up the initialization of ZP and USER variables from ROM tables, which should give us some good savings as well.

While you are in there, can you fix an omission on my part in xt_editor_line?  It should have underflow detection and doesn't.  It will need the UF bit added in the header as well.  All of the other editor words call a word that has underflow detection first, so they should be fine.

**Comment by SamCoVT** [comment] 2018-12-19 20:43
I think the POSTPONEd words are not as bad as I originally feared.  It looks like the POSTPONE is simply there to make words that would normally be immediate get compiled into the word to run later, and I don't actually have to assemblerize it at all - because I'm writing (in assembly) what the word is supposed to do when run, I can just `jsr xt_...` the postponed immediate words because, when my word runs, it _is_ supposed to do it then. Once I have the cold init from rom tables done, I'll give those words a try.  If it really is that easy, I should be able to clear out forth_word.fs except for the message at the bottom.

I hadn't seen that `execute-parsing` before.  I does almost exactly what I was pondering over in #201 for using parse-name to implement cleave, but for any word.  I might just give it a try to see what happens, and issue a pull request if it happens to work.

**Comment by SamCoVT** [comment] 2018-12-20 02:52
The flow control words really are that simple.  I've done `IF THEN ELSE REPEAT UNTIL ( .(` so far and plan to work on the rest tomorrow evening.  This should free up several hundred bytes, as well as greatly reducing the startup delay.

**Comment by scotws** [comment] 2018-12-20 13:11
Huh. I don't remember the exact reasons I left them high-level, just being very frustrated with the whole thing back in Tali 1 days; it was something with the difference between **postpone** affecting immediate and normal words. Whatever -- if they pass the test suite, let's by all means assemblerize them. I'll wait with the underflow conversion until you're done because a lot of those need checking as well.

**Comment by SamCoVT** [comment] 2018-12-21 03:56
Indeed, `POSTPONE` on a non-immediate word is a little trickier, but I figured it out.  The one that took me the longest to figure out is `DOES>`, which needs its two helper functions (which are normally compiled in xt_does) called directly instead.  

The assemblerization saved a good amount of bytes and we have just under 2K non-reserved ROM now.  That seems like a pretty good amount for a user to put their own words into.

**Comment by scotws** [comment] 2018-12-21 10:06
About 2 K should be enough, I agree. We'll leave this open for the moment for further ideas?

**Comment by SamCoVT** [comment] 2018-12-21 13:14
Sounds good.

**Comment by SamCoVT** [comment] 2018-12-30 02:01
The block editor words are currently just JSRs to the forth words.  There is some room to save some bytes by rewriting them in "real" assembly.  For that matter, there are quite a few words that are just JSRs to the various forth words - for more than 5-6 forth words, it's worth looking to see if it could be smaller in "real" assembly.

**Comment by scotws** [comment] 2019-01-03 15:02
I might be missing something here, but it seems that in the input history routine starting at the `_recall_history label` (about line 530), the following about 30 lines are exactly the same as those after `_done` (minus a few lines clearing bit 3). Could these be combined to a subroutine to save space?

**Comment by SamCoVT** [comment] 2019-01-03 15:13
Yes, the duplicate code in `xt_accept` could certainly be moved into a subroutine.  That would save around 30 bytes.

**Comment by scotws** [comment] 2019-01-03 19:49
For later: In `question_do_runtime`, about line 3200 of `native_words.asm`, there are some subroutine jumps that should be rewritten in assembler for speed -- this is where it should make a difference.

**Comment by scotws** [comment] 2019-01-03 21:23
In **s"**, about line 8680 in `native_words.asm`, we should be able to convert most of the comparisons into a loop where we compare the character with a string of legal characters, and use that index to get the ASCII value from a parallel string. That won't work for everything - **m** for instance needs to save two characters - but should save us some space.

**Comment by scotws** [comment] 2020-04-15 08:40
I'm closing this because a more modular design with 64tass might take care of a lot of these problems. If not, we can revisit it with the new code base.

**Closed by scotws** 2020-04-15 08:40 UTC
Labels: enhancement
